[INFO] [1713264982.228096880] [joystick_control]: Armed=False, Estop=False, mode=Reboot, Timestamp=1713264982.1962981,Roll=0.0, Pitch=0.0, Thrust=0.0, Yaw=0.0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/magnusdaroe/P4_DroneProject/install/drone/lib/drone/manual_cmd.py", line 86, in control_loop
    node.get_logger().info("Drone in reboot mode. Waiting for mode change.", end='\r')
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/impl/rcutils_logger.py", line 334, in info
    return self.log(message, LoggingSeverity.INFO, **kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/impl/rcutils_logger.py", line 287, in log
    detected_filters = get_filters_from_kwargs(**kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/impl/rcutils_logger.py", line 206, in get_filters_from_kwargs
    raise TypeError(
TypeError: parameter "end" is not one of the recognized logging options "['throttle_duration_sec', 'throttle_time_source_type', 'skip_first', 'once']"
